name: "Prompt reviewers to merge PRs on behalf of authors"

permissions:
  contents: read

on:
  pull_request_review:
    types:
      - submitted

jobs:
  merge-on-behalf-information-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >-
      (github.repository == 'DavidSpickett/llvm-project')
    steps:
      - name: Checkout Automation Script
        uses: actions/checkout@v4
        with:
          sparse-checkout: llvm/utils/git/
          ref: main

      - name: Setup Automation Script
        working-directory: ./llvm/utils/git/
        run: |
          pip install -r requirements.txt

      - name: Generate Merge On Behalf Comment
        run: |
          # Writes to a file "comments".
          python3 ./llvm/utils/git/github-automation.py \
            --token '${{ secrets.GITHUB_TOKEN }}' \
            pr-merge-on-behalf-information \
            --issue-number "${{ github.event.pull_request.number }}" \
            --author "${{ github.event.pull_request.user.login }}" \
            --reviewer "${{ github.event.review.user.login }}"

      - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
        if: always()
        with:
          name: workflow-args
          path: |
            comments