name: PR Greeter

on:
  pull_request_target:
   types: [ opened ]

permissions:
  pull-requests: write

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.repository == 'DavidSpickett/llvm-project'
    steps:
      - name: Setup Automation Script
        run: |
          curl -O -L --fail https://raw.githubusercontent.com/"$GITHUB_REPOSITORY"/main/llvm/utils/git/github-automation.py
          curl -O -L --fail https://raw.githubusercontent.com/"$GITHUB_REPOSITORY"/main/llvm/utils/git/requirements.txt
          chmod a+x github-automation.py
          pip install -r requirements.txt

      - name: Greet Author
        run: |
          ./github-automation.py \
            --token '${{ secrets.GITHUB_TOKEN }}' \
            pr-greeter \
            --issue-number "${{ github.event.pull_request.number }}"
