name: Release Task

permissions:
  contents: read

on:
  workflow_dispatch

jobs:
  uncomment-download-links:
    name: Uncomment download links
    runs-on: ubuntu-24.04
    permissions:
      contents: write # For updating the release message.

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-github

      - name: Checkout LLVM
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          sparse-checkout: llvm/utils/release/github-upload-release.py
          sparse-checkout-cone-mode: false

      - name: Uncomment Download Links
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./llvm/utils/release/./github-upload-release.py --token "$GITHUB_TOKEN" --release "vX.Y.Z-1" uncomment_download_links
